name: Label New Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write  # ✅ This is the key fix

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add "To Do" label to new issues
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            To Do
